### ISSUE TITLE
How to reproduce the performance of streaming ImageNet models?

### ISSUE THREAD

**Issue by HaitaoWen** [tyler-hayes/REMIND#2]
Hi! I want to reproduce the performance of streaming ImageNet models, and follow the steps in README to run the run_imagenet_experiment.sh file( same ImageNet ordering), but i get this result after training, which seems not to match the performance in the paper.

![1](https://user-images.githubusercontent.com/33919986/93781193-b2c99400-fc5b-11ea-91c8-6b4702be7ae0.png)

**Comment by tyler-hayes** [comment]
Hi @ORION-CS,

Which version of Python, PyTorch, and CUDA are you currently using? We have verified the code for the following package versions:
- Python 3.7.6
- PyTorch (GPU) 1.3.1
- torchvision 0.4.2
- NumPy 1.18.5
- FAISS (CPU) 1.5.2
- CUDA 10.1 (also works with CUDA 10.0)
- Scikit-Learn 0.23.1
- Scipy 1.1.0

**Comment by HaitaoWen** [comment]
Thanks for your reply @tyler-hayes .

My package versions:
- Python 3.7.6
- PyTorch (GPU) 1.4.0
- torchvision 0.5.0
- NumPy 1.18.1
- FAISS (CPU) 1.6.3
- CUDA 10.0
- Scikit-Learn 0.22.1
-  Scipy 1.4.1

I use pip to install FAISS, because the package installed through conda will output errors during training. I will try to use conda to install this package again, and retrain the model.

**Comment by tyler-hayes** [comment]
Hi @ORION-CS,

I would recommend changing the PyTorch and torchvision versions to match ours as well.

**Comment by HaitaoWen** [comment]
Thanks a lot! I recreate a new Conda virtual environment that is the same with yours and get a reasonable result.
![tmp](https://user-images.githubusercontent.com/33919986/94140393-c3694c80-fe9d-11ea-9b52-e2fa3b4f8e58.png)
