### ISSUE TITLE
Can this lifelong learning approach be applied to regression?

### ISSUE THREAD

**Issue by xujinjiang** [tyler-hayes/REMIND#4]
It's a great honor to be the first questioner of this project. I want to use incremental learning on a regression problem. I wonder if REMIND works well in this problem.

**Comment by tyler-hayes** [comment]
Hi @xujinjiang,

Thanks for your interest in our work! REMIND is general enough to be applied to regression models. You would just need to swap out the neural network classification model for a neural network regression model. Hope this helps!
